version: '1.0.0'
services:
  cache:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_CACHE_PORT}:${REDIS_CACHE_PORT}
    volumes:
      - redis-data:/var/lib/redis/data
    restart: unless-stopped
  database:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data:
  redis-data: